# Generates web_index_html.h from the built single-file web app.
#
# Usage:
#   npm run build
#   .\firmware\embed_webapp.ps1 -Html dist\index.html -Out firmware\e36_badge_wifi\web_index_html.h
#
# The generated header exposes WEB_INDEX_HTML[] (PROGMEM) and WEB_INDEX_HTML_LEN.
# If the header exists, the ESP32 firmware serves the companion app at "/".
param(
  [Parameter(Mandatory = $true)][string]$Html,
  [Parameter(Mandatory = $true)][string]$Out
)

if (-not (Test-Path -LiteralPath $Html)) {
  Write-Error "HTML file not found: $Html - run 'npm run build' first."
  exit 1
}

$bytes = [System.IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $Html))
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// Generated by embed_webapp.ps1 from the single-file web build - do not edit by hand.')
[void]$sb.AppendLine('#ifndef WEB_INDEX_HTML_H')
[void]$sb.AppendLine('#define WEB_INDEX_HTML_H')
[void]$sb.AppendLine('#include <Arduino.h>')
[void]$sb.AppendLine('const unsigned char WEB_INDEX_HTML[] PROGMEM = {')
for ($i = 0; $i -lt $bytes.Length; $i += 16) {
  $end = [Math]::Min($i + 15, $bytes.Length - 1)
  $row = (($bytes[$i..$end]) | ForEach-Object { '0x{0:x2}' -f $_ }) -join ','
  [void]$sb.AppendLine('  ' + $row + ',')
}
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('const unsigned int WEB_INDEX_HTML_LEN = sizeof(WEB_INDEX_HTML);')
[void]$sb.AppendLine('#endif // WEB_INDEX_HTML_H')

$dir = Split-Path -Parent $Out
if ($dir -and -not (Test-Path -LiteralPath $dir)) {
  New-Item -ItemType Directory -Path $dir -Force | Out-Null
}
[System.IO.File]::WriteAllText($Out, $sb.ToString(), [System.Text.Encoding]::ASCII)
Write-Output "Wrote $Out ($($bytes.Length) bytes, $([math]::Round($sb.Length / 1MB, 1)) MB header)"
